config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  get '/swimshow' => 'pages#swimshow'
  get '/show-dates' => 'pages#showdates'
  get '/special-events' => 'pages#special-events'
  get '/exhibitors' => 'pages#exhibitors'
  get '/retailers' => 'pages#retailers'
  get '/media' => 'pages#media'
  get '/travel' => 'pages#travel'
  get 'pages/about'
  get 'pages/dates'
  get 'pages/events'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/special_event.rb
class SpecialEvent < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def swimshow
  end

  def about
  end

  def dates
  end

  def specialevents
    @events = SpecialEvent.all
  end
end

app/controllers/special_event_controller.rb
class SpecialEventController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/special_event_helper.rb
module SpecialEventHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <p class="pull-left">Designed with &hearts; in miami by <a href="http://stiltmedia.com" target="_blank">stiltmedia</a> &nbsp;&nbsp;|&nbsp;&nbsp; © 2015 All Rights Reserved</p>
        <p class="pull-right">
          <span class="social"><i class="fa fa-facebook"></i></span>
          <span class="social"><i class="fa fa-twitter"></i></span>
          <span class="social-last"><i class="fa fa-instagram"></i></span>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag('https://s3.amazonaws.com/swim-show/Website+Images/swimshow_logo.svg', alt: 'Miami Swim Show logo'), root_path, class: 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                  <%= render 'layouts/links' %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_links.html.erb
<li class="dropdown">
    <%= link_to 'Swimshow', swimshow_path, class: 'dropdown-toggle' %>
    <ul class="dropdown-menu">
      <li><%= link_to 'Show Dates', show_dates_path %></li>
      <li><%= link_to 'Special Events', special_events_path %></li>
      <li><a target="_blank" href="https://s3.amazonaws.com/swim-show/Website+Images/FLOOR-PLAN-2015.pdf">Floor Plan</a></li>
      <li><%= link_to 'Exhibitors', exhibitors_path %></li>
      <li><%= link_to 'Retailers', retailers_path %></li>
      <li><%= link_to 'Media', media_path %></li>
      <li><%= link_to 'Travel', travel_path %></li>
    </ul>
</li>
<li><a href="#">Current Lines</a></li>
<li><a href="#">Gallery</a></li>
<li><a href="#">Classifieds</a></li>
<li><a href="#">News</a></li>
<li><a href="#">West Coast Regional</a></li>
<li><a href="#">About Us</a></li>
<li><a href="#">Contact</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwimShow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Page Loader -->
  <div class="page-loader">
    <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/loader.gif', alt: 'loader' %>
  </div>

  <%= render 'layouts/header' %>

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/dates.html.erb
<h1>Pages#dates</h1>
<p>Find me in app/views/pages/dates.html.erb</p>

app/views/pages/events.html.erb
<h1>Pages#events</h1>
<p>Find me in app/views/pages/events.html.erb</p>

app/views/pages/exhibitors.html.erb
<section class="exhibitors-head" role="banner">
  <div class="container-fluid">
    <div class="col-sm-12 col-md-4 col-md-offset-2 clearfix">
      <div class="top">
        <h1>Exhibitors</h1>
        <p>For immediate assistance and to request an exhibitor kit, please contact the SAF office directly</p>
        <br>
        <p><strong>Phone: 305.596.7889<br>Fax: 305.596.7713<br>E-mail: info@swimshow.com</strong></p>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

app/views/pages/home.html.erb
<section class="front-header" role="banner">
  <div class="container">
    <div class="col-sm-12 col-md-12 clearfix">
      <div class="top">
        <h1 class="title">GET READY...</h1>
        <h1 class="date">JULY 18-21</h1>
        <div class="detail-button">
          <a href="#pero-loco" class="btn scrolling-btn">Learn More</a>
        </div>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<section class="home-days" id="pero-loco">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-12">
        <h1>Days of Our SwimShow Lives</h1>
        <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/play.svg' %>
        <p>Take a quick peek and reminisce on your event packed days<br>at the SwimShow & LingerieShow!!</p>
      </div>
    </div>
  </div>
</section>

<section class="home-member">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h2>Are You In?</h2>
        <h3>MIAMI BEACH INcard</h3>
        <p>Get your Miami Beach INcard FREE TODAY at mbincard.com</p>
          <a href="#" class="btn btn-member">Get Now</a>
      </div>
      <div class="col-sm-12 col-md-6">
        <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/member.jpg', alt: 'INcard', class: 'img-responsive' %>
      </div>
    </div>
  </div>
</section>

<!-- COUNTER -->
<section class="section-counter">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Get Ready for July 18 - 21</h2>
      </div>
    </div>
    <div class="counter-wrap col-sm-12">
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">217</p>
        <h6 class="sub-info">Months</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">365</p>
        <h6 class="sub-info">Days</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">403</p>
        <h6 class="sub-info">Hours</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">189</p>
        <h6 class="sub-info">Seconds</h6>
      </div> <!-- end col-sm-3 -->
    </div> <!-- end counter-wrap -->
    <div class="col-sm-8 col-sm-offset-2">
      <div class="top-headline">
        <h3><em>...enjoy the <strong>SWIM!</strong></em></h3>
      </div> <!-- end headline -->
    </div> <!-- end col-sm-8 -->
  </div> <!-- end container -->
</section>
<!-- END COUNTER -->

app/views/pages/media.html.erb
<section class="media-head" role="banner">
  <div class="container-fluid">
    <div class="col-sm-12 col-md-4 col-md-offset-1 clearfix">
      <div class="top">
        <h1>Media<br>Requirements</h1>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<section class="media-content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/media.jpg', class: 'img-responsive' %>
      </div>
      <div class="col-sm-12 col-md-6">
        <p>The Swimwear Association of Florida is pleased to invite qualified working journalists from consumer and trade news organizations to submit registration requests and credentials for media access into the tradeshow.</p>
        <p>Media credentials are reserved for editorial media only which includes editors, producers, reporters, camera crews and/or still photographers. Any employee of a media outlet who does not work in an editorial capacity will not be eligible to receive a media badge.</p>
        <p>Please complete the media registration form via on-line or faxed to 305.596.7713. Media registration is not available on site at the tradeshow; it must be completed in advance in order to attain approval status.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="space">Please note:</p>
        <ol>
          <li>Submitting this application does not automatically qualify you for a press credential.</li>
          <li>A history of prior attendance does not guarantee approval or waive any aforementioned requirements.</li>
          <li>Misrepresentation of position and/or publication news organization will bar you and your organization from all future Swimwear Association of Florida events.</li>
          <li>Swimwear Association of Florida reserves the right to modify this policy without public notice and may deny any applicant a press credential.</li>
          <li>Press credentials are reserved for working members of the media only. Employees of media outlet who do not work in an editorial capacity are not qualified for a press credential.</li>
        </ol>
        <p class="space">Press credential will not be granted to:</p>
        <ol>
          <li>Advertising personnel, including directors, managers, account executives, marketing managers, public relations, promotions, accounting, graphic designers, etc.</li>
          <li>Editors of in-house newsletters.</li>
          <li>Media outlets and editorial personnel whose publication, website or journal does not cover or reflect this industry.</li>
          <li>Anyone whose purpose for attending is, in our judgment, for reasons other than generating news coverage of the event or its participants.</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<section class="media-content-2">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6 rightb">
        <h2>Media Requirements</h2>
        <ul>
          <li>Business card must include company name, contact name and editorial title (if your business card does not include an editorial title, an editorial credit/byline or masthead can be submitted)</li>
          <li>Recent masthead must be included</li>
          <li>Freelancers must submit a byline published within the last 6 months</li>
          <li>Print media must provide a recently published copy of the publication with attendees listed on the masthead or in byline of article</li>
          <li>Web publications must provide an existing secured site with relevant content that is updated on a continuing basis (personal web logs do not qualify)</li>
          <li>Freelance writers, video production companies and photographers must provide a letter from an editor or producer stating they are on assignment for an industry related publication</li>
        </ul>
      </div>
      <div class="col-sm-12 col-md-6">
        <p>Please mail sample publication and circulation figures to:</p>
        <p><strong>Publicity DepartmentSwimwear Association of Florida 8900 SW 117th Ave. Suite C-205 Miami, FL 33186</strong></p>
      </div>
    </div>
  </div>
</section>
<section class="pre-registration">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Online Media Registration</h1>
        <a href="#" class="btn btn-member">Registration</a>
      </div>
    </div>
  </div>
</section>

app/views/pages/retailers.html.erb
<section class="retailers-head" role="banner">
  <div class="container-fluid">
    <div class="col-sm-12 col-md-4 col-md-offset-2 clearfix">
      <div class="top">
        <h1>Retailer<br>Requirements</h1>
        <p>SwimShow is open to the trade only!</p>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>
<section class="retailer-content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/retailer-model.jpg', class: 'img-responsive' %>
      </div>
      <div class="col-sm-12 col-md-6">
        <p>Buyers can be admitted by presenting a minimum of three (3) of the following forms of business identification. Those indicated in boldface must be presented:</p>
        <ul>
          <li>Personalized business card listing your business address & job title</li>
          <li>Recent invoices showing purchases of finished swimwear products within the last year</li>
          <li>Account list</li>
          <li>Current retail business license or federal resale tax certificate (international businesses are required to show VAT)</li>
          <li>Imprinted business check</li>
          <li>Corporate credit card or proof of merchant credit card ID</li>
          <li>Credit reference sheet showing companies you purchase from</li>
          <li>Current year executed sales tax return or sales tax coupon book</li>
          <li>Lease agreement for commercial space</li>
          <li>Document from chamber of commerce</li>
          <li>Original letter of intent from an attorney or bank on official letterhead stating the intent to start a new business (this is acceptable for new businesses only)</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>Plus one of the following forms of personal photo identification is required:</p>
        <ul>
          <li>Driver’s license or passport</li>
          <li>Government issued photo ID</li>
          <li>Credit card or bank card with photo</li>
        </ul>
        <br>
        <p>For veteran attendees, there is no need to supply credentials. Just fill out the retailer Pre-Registration form on this site BUT, if you are bringing new buyers who have never attended the show, each new buyer must provide the appropriate documents. A guest of a pre-registered buyer can get their badge at the pre-registration kiosks but must be accompanied by the buyer.</p>
        <br>
        <p>We reserve the right to request updated credentials at any time. This is a necessary function in order to keep our database current.</p>
        <br>
        <p><strong>Questions? Call 305.596.7889 or email info@swimshow.com<br>Please email credentials to info@swimshow.com</strong></p>
      </div>
    </div>
  </div>
</section>
<section class="pre-registration">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Online Pre-Registration</h1>
        <a href="#" class="btn btn-member">Pre-Registration</a>
      </div>
    </div>
  </div>
</section>

app/views/pages/showdates.html.erb
<section class="showdates-head" role="banner">
  <div class="container-fluid">
    <div class="col-sm-12 col-md-6 clearfix">
      <div class="top">
        <h1>Show Dates</h1>
        <p>Save these dates for spectacular swimwear and lingerie</p>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<section class="dates">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h2>SwimShow</h2>
        <h3>July 18-21, 2015</h3>
        <p>Swim, run, fly or cruise your way to the 33rd annual SwimShow, sponsored by the Swimwear Association of Florida</p>
        <p><strong>Show Hours:<br>9am to 6pm: Saturday, Sunday, Monday<br>9am to 5pm: Tuesday</strong></p>
        <p>Check out the latest lines from around the globe in swimwear, accessories, beachwear and lingerie…over four days of dazzling celebrations and inspirations. Be among the first to see and share the latest in designs, trends, colors and brands!</p>
      </div>
      <div class="col-sm-12 col-md-6">
        <%= image_tag 'https://s3.amazonaws.com/swim-show/Website+Images/dates.jpg', class: 'img-responsive' %>
      </div>
    </div>
  </div>
</section>

<!-- COUNTER -->
<section class="section-counter">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Get Ready for July 18 - 21</h2>
      </div>
    </div>
    <div class="counter-wrap col-sm-12">
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">217</p>
        <h6 class="sub-info">Months</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">365</p>
        <h6 class="sub-info">Days</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">403</p>
        <h6 class="sub-info">Hours</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">189</p>
        <h6 class="sub-info">Seconds</h6>
      </div> <!-- end col-sm-3 -->
    </div> <!-- end counter-wrap -->
    <div class="col-sm-8 col-sm-offset-2">
      <div class="top-headline">
        <h3><em>...enjoy the <strong>SWIM!</strong></em></h3>
      </div> <!-- end headline -->
    </div> <!-- end col-sm-8 -->
  </div> <!-- end container -->
</section>
<!-- END COUNTER -->

<section class="dates-btm">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Feature Dates</h1>
        <p>(To Be Determained)</p>
      </div>
    </div>
  </div>
</section>

app/views/pages/special-events.html.erb
<section class="special-head">
  <div class="container">
    <div class="col-sm-12 clearfix">
      <div class="top">
        <h1>Special Events</h1>
      </div>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<section class="special-events">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Breakfast Bar</h1>
              <p>Saturday - Tuesday<br>9:00 - 10:30am Daily</p>
              <br>
              <a href="#" class="btn btn-member">View 2013 Images</a>
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>High Tea</h1>
              <p>Saturday - Tuesday<br>3:30 - 4:30pm Daily</p>
              <br>
              <a href="#" class="btn btn-member">View 2013 Images</a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Trend Seminars</h1>
              <p>Saturday, 12:30 - 1:30pm Daily<br>Monday, 11:00 - Noon</p>
              <br>
              <a href="#" class="btn btn-member">View 2013 Images</a>
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Swim Lounge</h1>
              <p>Saturday & Monday Evenings<br>6:00 - 7:30pm</p>
              <br>
              <a href="#" class="btn btn-member">View 2013 Images</a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Fashion Show & After Party</h1>
              <p>Sunday 6:00pm</p>
              <br>
              <ul>
                <li><a href="#" class="btn btn-member">View 2013 Images</a></li>
                <li><a href="#" class="btn btn-member">View 2013 Video</a></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Informal Modeling</h1>
              <p>Saturday & Monday<br>1:30 - 2:00pm</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Tech Lounge</h1>
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <div class="box">
              <h1>Art Entertainment</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section>
  <% @events.each do |se| %>
    <%= se.title %>
  <% end %>
</section>

app/views/pages/swimshow.html.erb
<section class="swim-header">
  <div class="container">
    <div class="col-sm-12 col-md-6 clearfix">
      <h1>SwimShow & Lingerie Show</h1>

      <p>Welcome to the SwimShow & LingerieShow and thank you for your interest in the largest and most significant swimwear tradeshow in the world.</p>
      <p>The annual SwimShow is an essential show for the industry—a platform for building relationships, enjoying the latest trends in swimwear and lingerie, and connecting buyers and suppliers. Recognized as the launching pad for many of the industry’s leading lines, SwimShow is hosted in Miami Beach, the swim fashion capital of the world!</p>
      <p>We welcome exhibitors and buyers from all around the world to join in this one-of-a-kind show that showcases more than 2,500 lines and now offers more space for exhibitors featuring new swimwear and lingerie lines.</p>
      <p>The show draws more than 2,500 buyers from 60 different countries spanning the globe. It is the largest swimwear tradeshow in the world and the first opportunity for buyers to see the latest designs for the upcoming cruise season.</p>

      <h2>Miami Beach Convention Center</h2>
      <h3>1901 Convention Center Drive</h3>
      <h4>Miami Beach, FL 33139</h4>
      <h4>Halls A, C & D</h4>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<section class="swim-sect-2" role="banner">
  <div class="container">
    <div class="col-sm-12 col-md-6 col-md-offset-6 clearfix">
      <h1>About The Show</h1>
      <h3>Dive in to the world’s biggest,  boldest and best swim show!</h3>
      <p>Turning heads and turning out trends for more than three decades, SwimShow 2015 will provide even more sizzle this year by adding 500,000 square feet of exhibition space for more hot new brands, designers and swimwear sensations. The bigger-and-better-than-ever SwimShow 2015 will feature:</p>
      <p>More of the finest women’s, men’s, children’s, resort & lifestyle and accessory collections from across the globe</p>
      <p>This can’t-miss show offers exclusive access to the latest trends in swimwear and lingerie, stunning sights and events, and a true celebration of the simple luxury of swimwear!</p>
      <p>July 18-21, 2015…enjoy the SWIM!</p>
    </div> <!-- end col-sm-10 -->
  </div>	<!-- end container -->
</section>

<!-- COUNTER -->
<section class="section-counter">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Get Ready for July 18 - 21</h2>
      </div>
    </div>
    <div class="counter-wrap col-sm-12">
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">217</p>
        <h6 class="sub-info">Months</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">365</p>
        <h6 class="sub-info">Days</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">403</p>
        <h6 class="sub-info">Hours</h6>
      </div> <!-- end col-sm-3 -->
      <div class="col-sm-6 col-md-3">
        <p class="counter-number">189</p>
        <h6 class="sub-info">Seconds</h6>
      </div> <!-- end col-sm-3 -->
    </div> <!-- end counter-wrap -->
    <div class="col-sm-8 col-sm-offset-2">
      <div class="top-headline">
        <h3><em>...enjoy the <strong>SWIM!</strong></em></h3>
      </div> <!-- end headline -->
    </div> <!-- end col-sm-8 -->
  </div> <!-- end container -->
</section>
<!-- END COUNTER -->
<section class="swim-sect-3">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Check Out The Floor Plan</h1>
        <a target="_blank" href="https://s3.amazonaws.com/swim-show/Website+Images/FLOOR-PLAN-2015.pdf" class="btn btn-member">View Floorplan</a>
      </div>
    </div>
  </div>
</section>